name: Push
on:
  push:
    branches:
      - master

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@evrone-erp'
      - name: Git Identity
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/$GITHUB_REPOSITORY
          npm  set "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}"
      - run: cp .npmrc.example .npmrc
      - name: Install
        run: yarn install
      - name: "Version and publish"
        run: |
          npx lerna version --conventional-commits --yes
          npx lerna publish from-git --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

