name: Push
on:
  push:
    branches:
      - master

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: '12'
          cache: 'yarn'
      - name: Configure npmrc
        run: cp .npmrc.example .npmrc
      - name: "Version and publish"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor}}@users.noreply.github.com"
          npx lerna version --conventional-commits --conventional-graduate --yes
          npx lerna publish from git --yes
